### ISSUE TITLE
Parse enrollCode for lectures with no sections

### ISSUE THREAD

**Issue by kmai12** [UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum#13]
The lectures and sections seem to be correctly parsing.
Enroll codes are only present in sections and not in lectures. However, there are some lectures with no sections at all, such as CMPSCCS 130A of Spring 2014. These lectures DO have Enroll codes.

Add an enrollCode data member inside UCSBLecture.java and add/edit the appropriate getters/setters/toString methods.

Parse the enroll code for lectures that have no sections.

~estimated 100

**Comment by EasterAndJay** [comment]
Approved 100pts

**Comment by EasterAndJay** [comment]
Closed
