### ISSUE TITLE
String Index out of Bounds Exception error

### ISSUE THREAD

**Issue by natashalee** [UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum#21]
Sometimes when we make a search in the gui, a String Index Out of Bounds Exception come up. But after going into the webpage, making the same search, then going back to the gui, it seems to search fine. 
Before refreshing on the actual webpage: 
<img width="458" alt="screen shot 2016-03-03 at 6 21 47 pm" src="https://cloud.githubusercontent.com/assets/15113672/13516317/efb5560a-e16d-11e5-9584-a8e251ea6f8c.png">

After:
<img width="449" alt="screen shot 2016-03-03 at 6 27 38 pm" src="https://cloud.githubusercontent.com/assets/15113672/13516321/f4411812-e16d-11e5-9818-4be00e9578c8.png">

This only happens sometimes. 

(300 points)

**Comment by EasterAndJay** [comment]
W16 approved

**Comment by MadRubicant** [comment]
Reassessing at 200 points

**Comment by MadRubicant** [comment]
F16 OK (200 pts)

**Comment by pconrad** [comment]
Issue fixed in Commit 6e80aed
