### ISSUE TITLE
GUI selection boxes

### ISSUE THREAD

**Issue by natashalee** [UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum#22]
As of now, the gui selection boxes are hardcoded lists (example: subject includes "ANTH" or "BIO" literal strings in a array). It would be better to scrape these lists directly from the webpage so that if the names of the subjects were to change or new subjects were to be added, the scraper would still work and be up to date. 

(300 points)

**Comment by EasterAndJay** [comment]
W16 approved

**Comment by MadRubicant** [comment]
F16 OK (300 pts)

**Comment by natashalee** [comment]
#44 created to fix this and the year selection box
