### ISSUE TITLE
Javadoc publishing

### ISSUE THREAD

**Issue by MadRubicant** [UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum#26]
Currently, the javadocs attempt to publish to CSIL. Instead, they should be published using the Github-Pages workflow

50 pts

**Comment by MadRubicant** [comment]
F16 OK (50 pts)

**Comment by pconrad** [comment]
@MadRubicant : I advised @jimvargas and @ryoung141 to publish their javadoc to this repo:

https://github.com/UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum-javadoc

**Comment by pconrad** [comment]
Oh: also I made gh-pages the default branch in https://github.com/UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum-javadoc so @jimvargas and @ryoung141 should do a pull request to the gh-pages branch when they do their pull request.

It should publish at: https://github.com/UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum-javadoc/javadoc/index.html

**Comment by pconrad** [comment]
Oh, and while @MadRubicant is the original mentor that curated this repo, @ryoung141 just reminded me that @Tektonbuilds (Franklin) is actually the mentor for this repo.

**Comment by Tektonbuilds** [comment]
Got it!
