### ISSUE TITLE
Exception thrown when quarter does not exist

### ISSUE THREAD

**Issue by MadRubicant** [UCSB-CS56-Projects/cs56-scrapers-ucsb-curriculum#34]
The scraper throws an exception when a quarter is not on the public-facing list of quarters and searched for. To reproduce, start the GUI and search for Winter 2014, any department. 
Implementing #22 should help fix this, and #21 is likely related. 

100 pts

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by natashalee** [comment]
no longer an issue because quarters are now scraped with the right pairings of quarter and year. closing.
