### ISSUE TITLE
Refactor UCSBCurriculumSearch

### ISSUE THREAD

**Issue by jlguida** [ucsb-cs56-projects/cs56-scrapers-ucsb-curriculum#53]
Right now UCSBCurriculumSearch is long and hard to understand. It could use refactoring.

300 points

**Comment by natashalee** [comment]
F17OK 300 points

**Comment by CDLlo** [comment]
W18 OK 200 points

**Comment by nathan-inge** [comment]
This was addressed as part of #56. Brand new `loadCoursesJsoup` along with 7 helper functions. Old `loadCourses` and its helper methods can eventually be removed now.
